INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME)
    VALUES (0, 'sales');

INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME)
    VALUES (1, 'human resources');

INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME)
    VALUES (2, 'engineering');

UPDATE EMPLOYEE SET EMPLOYEE_SUPER_ID=4;

SELECT * FROM EMPLOYEE;

SELECT * FROM ADDRESS;

SELECT * FROM EMPLOYEE_TITLE;